version: '3.9'
services:
  api:
    hostname: api
    image: notik-api
    ports:
      - '8080:80'
    environment:
      - ConnectionStrings__PostgreSQL_Dev=Server=
      - JwtConfig__Secret=
      - Auth__ApiKey=
      - AllowedHosts=*
